// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx7zOTReDP1MsDfybNCNCvtiFVpbBeTE4',
    appId: '1:376857819294:web:c7eef91e7c617d9477a38f',
    messagingSenderId: '376857819294',
    projectId: 'photo-ai-app-77e5d',
    authDomain: 'photo-ai-app-77e5d.firebaseapp.com',
    storageBucket: 'photo-ai-app-77e5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3t6i8vKXCEpvN8gRnb1yAuS4tfSVWBkA',
    appId: '1:376857819294:android:543075a03d89fce077a38f',
    messagingSenderId: '376857819294',
    projectId: 'photo-ai-app-77e5d',
    storageBucket: 'photo-ai-app-77e5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMt2Tiy6mHg34euaLSiITfZvsmWbjoQs',
    appId: '1:376857819294:ios:0e67c345b408e07577a38f',
    messagingSenderId: '376857819294',
    projectId: 'photo-ai-app-77e5d',
    storageBucket: 'photo-ai-app-77e5d.firebasestorage.app',
    iosBundleId: 'com.example.photoAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMt2Tiy6mHg34euaLSiITfZvsmWbjoQs',
    appId: '1:376857819294:ios:0e67c345b408e07577a38f',
    messagingSenderId: '376857819294',
    projectId: 'photo-ai-app-77e5d',
    storageBucket: 'photo-ai-app-77e5d.firebasestorage.app',
    iosBundleId: 'com.example.photoAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx7zOTReDP1MsDfybNCNCvtiFVpbBeTE4',
    appId: '1:376857819294:web:11323356ae9fa66177a38f',
    messagingSenderId: '376857819294',
    projectId: 'photo-ai-app-77e5d',
    authDomain: 'photo-ai-app-77e5d.firebaseapp.com',
    storageBucket: 'photo-ai-app-77e5d.firebasestorage.app',
  );
}
